### ISSUE TITLE
[question] about parallels-iso build with packer 0.7.1

### ISSUE THREAD

**Issue by lmayorga1980** [joefitzgerald/packer-windows#105]
It would be nice if we can add support for parallels. I've tried to build a vagrant box but it seems that something is broken.

It is really weird that i get a Windows Installation Error (Error Creating Partition) when using Parallels-Iso but it just works with Vmware-Iso and Virtualbox-Iso. 

https://github.com/mitchellh/packer/issues/1494

**Comment by mefellows** [comment]
I would love to see an example setup, I've taken a working setup for the virtualbox-iso builder and reconfigured with a parallels-iso setup that fails with the same issue @lmayorga1980 was having from above ("could not create a partition on disk 0..."). I'm sure it has something to do with the IDE setup but not sure what to change.

@joefitzgerald - I'm interested in your comments from above on how to compare configurationns. Are you referring to the config.pvs file or something else? And what is the file Packer is generating? I'm happy to dig deep but if you have more detail I would love to hear it.

Here is my setup for reference (heavily taken from scripts in this repo): https://gist.github.com/mefellows/a035f26be9e6f45df384

**Comment by rickard-von-essen** [comment]
This setup works quite well for me:
https://github.com/rickard-von-essen/packer-windows/tree/parallels

Except that I from time to time hit https://github.com/mitchellh/packer/issues/1872 .
And that the install of _Parallels Tools_ is tricky. I don't know how to detect when it is finished. Currently I just add a 2 minutes sleep after kicking of the install. Hoping that it will be enough for the install to be done. I just started a thread asking for a solution to this, see http://goo.gl/hbCvwc .

**Comment by rickard-von-essen** [comment]
@mefellows Your config contains 
```json
["set", "{{.Name}}", "--size","65536"]
```
That don't work. First of all yo already configured the size of the disk and a proper prlctl command would be something like:
```prlctl set <VM> --device-set hdd0 --size 65536```

**Comment by mefellows** [comment]
Thanks @rickard-von-essen that's great. I've been able to adapt the `answer_files/81/Autounattend.xml` file to work with Windows 2012r2 nicely. As Joe mentioned it's all about the disk configuration and this is what works:

```xml
            <DiskConfiguration>
                <Disk wcm:action="add">
                    <CreatePartitions>
                        <CreatePartition wcm:action="add">
                            <Order>1</Order>
                            <Type>Primary</Type>
                            <Size>60000</Size>
                        </CreatePartition>
                    </CreatePartitions>
                    <ModifyPartitions>
                        <ModifyPartition wcm:action="add">
                            <Extend>false</Extend>
                            <Format>NTFS</Format>
                            <Letter>C</Letter>
                            <Order>1</Order>
                            <PartitionID>1</PartitionID>
                            <Label>Windows 81</Label>
                        </ModifyPartition>
                    </ModifyPartitions>
                    <DiskID>0</DiskID>
                    <WillWipeDisk>true</WillWipeDisk>
                </Disk>
                <WillShowUI>OnError</WillShowUI>
            </DiskConfiguration>
            <ImageInstall>
                <OSImage>
                    <InstallTo>
                        <DiskID>0</DiskID>
                        <PartitionID>1</PartitionID>
                    </InstallTo>
                    <WillShowUI>OnError</WillShowUI>
                    <InstallToAvailablePartition>false</InstallToAvailablePartition>
                    <InstallFrom>
                        <MetaData wcm:action="add">
                            <Key>/IMAGE/NAME </Key>
                            <Value>Windows Server 2012 R2 SERVERSTANDARD</Value>
                        </MetaData>
                    </InstallFrom>
                </OSImage>
            </ImageInstall>
```
Strangely, I also need to use the `"guest_os_type": "win-8.1",` option in `packer.json` otherwise it still doesn't work (similar issues to above).

**Comment by it-is-just-me** [comment]
In my case it only worked when disabling EFI (efi-boot):
```
"prlctl": [
        ["set", "{{.Name}}", "--cpus", "{{user `cpu_cores`}}"],
        ["set", "{{.Name}}", "--memsize", "{{user `memory_size`}}"],
        ["set", "{{.Name}}", "--efi-boot", "off"]
      ]
```
