### ISSUE TITLE
Windows 10 Preview - anyone want to get started?

### ISSUE THREAD

**Issue by ferventcoder** [joefitzgerald/packer-windows#108]
http://windows.microsoft.com/en-us/windows/preview-iso

English (x64):
 * http://iso.esd.microsoft.com/W9TPI/FD54DF81A4CCF4511BA1445C606DDBA2/WindowsTechnicalPreview-x64-EN-US.iso
 * SHA1 EB75A3D3C0F621F175B75DC65DB036D0E00EAC43
 * Key: NKJFK-GPHP7-G8C3J-P6JXR-HQRJR

**Comment by StefanScherer** [comment]
Just tried build 9926 Enterprise Technical Preview ISO. It seems that floppy support is back.

**Comment by StefanScherer** [comment]
See PR #132 for a first working template.

**Comment by StefanScherer** [comment]
Just merged #132 and #144 into master.
