### ISSUE TITLE
Other Port for RDP

### ISSUE THREAD

**Issue by StefanSchoof** [joefitzgerald/packer-windows#110]
I created a Windows 2012 R2 Box on a Windows Host. After a Vagrant up and Vagrant rdp, I got the message "Your computer could not connect to another console session on the remote computer because you already have a console session in progress."

In the Template the 3389 Port is forwarded to the same Port on the Host. https://github.com/joefitzgerald/packer-windows/blob/master/vagrantfile-windows_2012_r2.template#L18
After adding the line

```
config.vm.network "forwarded_port" , guest: 3389, host: 33389
```

to my local Vagrantfile I can connect to the vm.

I think rdp tries to connect to my windows host and not the guest. Should the Hostport in the template file updated to prevent this on windows host?

**Comment by majkinetor** [comment]
I got the same error and the remedy was the same.
Vagrant 1.7.2 with Windows Server 2012 r2 in admin console. `mstsc` worked too.
