### ISSUE TITLE
Add comments about <key> to Windows 8.1 Autounattend.xml

### ISSUE THREAD

**Issue by jreadytalk** [joefitzgerald/packer-windows#114]
It would be good to add comments about `<key>` to the Autounattend.xml for Windows 8.1. Comments like those found in other Autounattend.xml files:

```
<!-- You must uncomment the Key element (and optionally insert your own key) if you are using retail or volume license ISOs -->
<!--<Key>D2N9P-3P6X9-2R39C-7RTCD-MDVJX</Key>-->
```

I couldn't get my retail license working without it. If Windows 8's evaluation distribution needs an (un-&lt;key&gt;-wrapped) value there, then we'll have to tweak the comment a bit to say "just wrap your key string in `<key>`".

**Comment by jalessio** [comment]
I stumbled across this issue after submitting a pull request for the same thing. See https://github.com/joefitzgerald/packer-windows/pull/133/ for what I think is basically an in-line documentation/consistency improvement.
