### ISSUE TITLE
OpenSSHd exit status not being passed back to packer

### ISSUE THREAD

**Issue by stonith** [joefitzgerald/packer-windows#123]
Hi,

I'm trying catch failed provisioner steps but found that opensshd doesn't seem to return exit codes properly for packer to fail.

Windows target:

```
#ssh vagrant@192.168.0.10 whoamia
/bin/sh: whoamia: command not found
#echo $?
0
```

Linux target:

```
#ssh localhost whoamia
bash: whoamia: command not found
#echo $?
127
```

Anyone else running into the same issue?

**Comment by lmayorga1980** [comment]
:+1:
