### ISSUE TITLE
Minor nit: Chocolatey no longer installed at C:\Chocolatey

### ISSUE THREAD

**Issue by lonniev** [joefitzgerald/packer-windows#129]
There's a comment in chocopacks.bat that the script needs to assure that C:\Chocolatey is in the path. Some recent time ago, the installer changed to installing chocolatey into c:\ProgramData\chocolatey.

The old comment is now just confusing.

Also, loading the path from some cruft file named "PATH" in C:\Windows\TEMP left behind by a peer script that might not have run is a pretty unreliable bit of code.

**Comment by sneal** [comment]
Closing, this batch file no longer exists.
