### ISSUE TITLE
Add support for Windows Nano Server

### ISSUE THREAD

**Issue by ferventcoder** [joefitzgerald/packer-windows#147]
Any thoughts yet on this?

**Comment by joefitzgerald** [comment]
Can you elaborate?

**Comment by lmayorga1980** [comment]
https://msdn.microsoft.com/en-us/library/mt126167.aspx

**Comment by joefitzgerald** [comment]
:thumbsup:

**Comment by ferventcoder** [comment]
What @lmayorga1980 stated. :)

**Comment by joefitzgerald** [comment]
I want this because I want to see if Cloud Foundry's Diego rewrite / .NET support runs on it. Are there any licensing subtleties to be aware of?

**Comment by ferventcoder** [comment]
Probably the same licensing that goes along with Windows.

**Comment by kensykora** [comment]
Is there an image or ISO we can play with?

**Comment by ferventcoder** [comment]
https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-technical-preview

**Comment by StefanScherer** [comment]
:+1: for Nano Server ;-)
The Server 2016 Technical Preview 2 ISO has a folder with this content

```
D:\NanoServer>type ReadMe.txt
For detailed information on deploying and managing Nano Server, please go to this link: http://www.aka.ms/nanoserver
D:\NanoServer>dir
 Volume in drive D is J_SSS_X64FRE_EN-US_DV9
 Volume Serial Number is EFD5-541D

 Directory of D:\NanoServer

04/25/2015  07:28 AM    <DIR>          .
04/25/2015  07:28 AM    <DIR>          ..
04/25/2015  07:28 AM       145,474,203 NanoServer.wim
04/25/2015  07:28 AM    <DIR>          Packages
04/25/2015  07:28 AM               116 ReadMe.txt
               2 File(s)    145,474,319 bytes
               3 Dir(s)               0 bytes free
```

**Comment by halr9000** [comment]
:thumbsup:

**Comment by joefitzgerald** [comment]
Wondering if anyone has done experimentation here. Anyone tried to work with nano server in AIK yet? I very much want this in the repo.

**Comment by halr9000** [comment]
Paging @mwrock? http://www.hurryupandwait.io/blog/a-packer-template-for-windows-nano-server-weighing-300mb

**Comment by mwrock** [comment]
Here is one I created from TP4 and works for me. It grabs the 2016 TP4 ISO, creates an interem server 2016 image, builds the nano image from that on a different partition and finally removes the 2016 server partition.

https://github.com/mwrock/packer-templates/blob/master/vbox-nano.json

You are welcome scavenge and copy over here.

**Comment by mwrock** [comment]
The built box is publicly hosted on atlas: mwrock/WindowsNano

**Comment by StefanScherer** [comment]
In the meantime there is a smaller Nano download available. 

http://blogs.technet.com/b/nanoserver/archive/2016/01/07/download-just-nano-server-in-a-vhd-windows-server-2016-technical-preview-4.aspx

Put probably a VHD won't help for packer.

**Comment by StefanScherer** [comment]
Closing. Microsoft has decided to drop NanoServer as VM and only use it in Windows Containers.
