### ISSUE TITLE
VSphere Support?

### ISSUE THREAD

**Issue by tomswaby** [joefitzgerald/packer-windows#148]
Hi Joe,

Great contribution - i've been using this successfully in vagrant its great. Just wondering what you'd need to do to add vSphere support to the code? It'd be hugely beneficial...

Thanks

**Comment by joefitzgerald** [comment]
Hey Tom. You should be able to use this with vSphere today by adding the vSphere post-processor to your .json: https://packer.io/docs/post-processors/vsphere.html

**Comment by StefanScherer** [comment]
There also is this packer post processor at https://github.com/frapposelli/packer-post-processor-better-vsphere, but I don't know the status of it. Fabio then implemented packer post processors vor vCenter and vCloud at https://github.com/gosddc/packer-post-processor-vagrant-vmware-ovf.

**Comment by sneal** [comment]
Post-process is the current supported way to go. It would be nice to directly work against vSphere, but that would need to be added to core Packer.
