### ISSUE TITLE
Windows cannot read the <ProductKey> setting from the unattend answer file

### ISSUE THREAD

**Issue by stagor** [joefitzgerald/packer-windows#151]
Hi,

I am receiving the following error when trying to build an image from `windows_2012_r2.json`: "Windows cannot read the <ProductKey> setting from the unattend answer file".
I downloaded iso and put it into ./iso folder. I googled answers in the Internet and there was a suggestion to turn off the floppy drive. It helped, however how then we can specify all necessary files for provisioning?

Please, advise how to resolve the issue if you have ever faced with it.

Cheers.

**Comment by StefanScherer** [comment]
Which ISO do you use? 
The trial ISO should work out of the box without manual download.

Other ISO's may need a change in the answer_files/2012_r2/Autounattend.xml. Look for the key there and the comments in the XML.

The floppy is needed to feed the windows installer ;-)

**Comment by StefanScherer** [comment]
@stagor look at these lines https://github.com/joefitzgerald/packer-windows/blob/270f8778bc006afddd0b88092349e7d5df6d25b9/answer_files/2008_r2/Autounattend.xml#L34-40

**Comment by stagor** [comment]
Hi Stefan, thank you for your quick response. You were right about ISO, as it was turned out, my colleague gave me a different distrib and renamed it with the name I requested. Shame, I spent lots of time yesterday but the problem was so obvious. I have re-downloaded a correct one and now I can see it's in progress. Cheers. All good now.
