### ISSUE TITLE
Windows 8 Confirm Popup on Install

### ISSUE THREAD

**Issue by Skarlso** [joefitzgerald/packer-windows#156]
Hey Guys. 

Upon windows 8 install, I noticed that before the setup, there is a frigging pop which waits for you to click on Next to continue. Everything after that works excellent. 

Does anyone have any idea how to avoid that frigging pop-up? This is before anything start. Just a windows which says => you are about to install... bla. Like I have to be told that?? Damn it. :) 

Anyhow. Any ideas? 

Thank you!! 
Gergely.

**EDIT**: 

Got the bastard. It's a "Select The operating system you would like to install" dialogue which is not escaped / disabled in the answer file.

http://misheska.com/blog/2013/07/27/windows-8-automated-install-settings/

**Comment by Skarlso** [comment]
Fixed it. 

Needed to amend the answer file because my operating system was named differently. 

This is I had to edit, in case somebody is bumping into this as well: 

                    <InstallFrom>
                        <MetaData wcm:action="add">
                            <Key>/IMAGE/NAME</Key>
                            <Value>Windows 8.1 Pro N</Value> <----- THIS HERE
                        </MetaData>
                    </InstallFrom>

**Comment by dsudduth** [comment]
Thanks @Skarlso, your follow up helped me out.

**Comment by Skarlso** [comment]
You are most welcome. Glad I could help out. :)

**Comment by larytet** [comment]
+1 - similar problem
