### ISSUE TITLE
2008R2 Windows Updates hangs

### ISSUE THREAD

**Issue by markhuber** [joefitzgerald/packer-windows#159]
I've spent the better part of the day trying to troubleshoot this one to no avail. 

From a clean clone, enabling gui, and building the windows_2008_r2.json when the answer file reaches win-updates.ps1 , it gets stuck at the first call to $script:UpdateSearcher.Search . 

In addition if you skip that and attempt to use the GUI to run windows updates, it will install the latest windows update agent, but then get stuck on Checking for Updates.

Can anyone else confirm this issue? I believe this is a Windows Update bug, but I've tried every hack and slash trick to repair it on google to no avail.

**Comment by markhuber** [comment]
After leaving this running over night it does actually complete, but based on the timing it looks like it adds about 4 hours to the completion. I know it spends at least the first hour doing seemingly nothing. 

I'll close this issue in a few days if no one has any feedback.

**Comment by joefitzgerald** [comment]
@markhuber There is such a massive amount of updates for Windows 2008 R2, it's possible the first hour is spend just _downloading stuff_.

**Comment by dylanmei** [comment]
You might consider tweaking MaxUpdatesPerCycle further. Check out this issue: https://github.com/joefitzgerald/packer-windows/pull/135

**Comment by sneal** [comment]
Windows 2008R2 updates often take 4-6 hours to complete. Consider upgrading to Windows 2012R2, it _only_ takes 1 to 2 hours :wink:

This is why I used to chain all my Packer builds using the ISO build -> VMX builder where the ISO builder just applies Windows updates and subsequent builds specialize the box into a web server etc.
