### ISSUE TITLE
Windows 10 TH2 fails to select Operating System

### ISSUE THREAD

**Issue by chrisgannon6** [joefitzgerald/packer-windows#183]
I'm using windows_10.json its associated Autounattend.xml  to install the recently released Windows 10 TH2 with Packer. It's getting stuck on the select Operating system page. 

I've modified the iso url and sha1 key to:
"iso_url": "http://care.dlservice.microsoft.com/dl/download/B/B/3/BB3611B6-9781-437F-A293-AB43B85C2190/10586.0.151029-1700.TH2_RELEASE_CLIENTENTERPRISEEVAL_OEMRET_X64FRE_EN-US.ISO",
"iso_checksum_type": "sha1",
"iso_checksum": "93845bbcc9677000df76cb2a5267c8eb52995bae",

Autounattend.xml I've left unmodified. The operating system name being displayed during install is still "Windows 10 Enterprise Evaluation" matching the <Value> tag.  I thought there may be a new key to go into the ProductKey tag but I can't see any on the relevant Microsoft pages. 

Has anyone else tried this with or without success?

**Comment by joefitzgerald** [comment]
You may need to create a new autounattend with the Windows Installation Kit to determine the right key to put in the existing file.

**Comment by StefanScherer** [comment]
@chrisgannon6 Haven't tried it yet. You may check the names by mounting the ISO in another Windows VM and run `dism /Get-WimInfo /WimFile:d:\sources\install.wim`

**Comment by chrisgannon6** [comment]
Thanks! Appreciate the suggestions. I'll give that a go.

**Comment by chrisgannon6** [comment]
All sorted. The name was "Windows 10 Enterprise Evaluation Technical Preview". 

Appreciate the prompt assistance from both of you.

**Comment by StefanScherer** [comment]
@chrisgannon6 Glad we could help. Do you want to send a PR to update the win10 template for all users of this repo? Just to kerp it up-to-date.
