### ISSUE TITLE
Windows 10 box can't be built with Windows Updates disabled

### ISSUE THREAD

**Issue by avtar** [joefitzgerald/packer-windows#186]
Attempting to create a Windows 10 box [with Windows updates disabled](https://github.com/joefitzgerald/packer-windows/blob/master/answer_files/10/Autounattend.xml#L260-L265) will result in a [failed build](https://gist.githubusercontent.com/anonymous/1754787ee61d4ac9d2bd/raw/b542a36d5febb5bcaa3c8f895c45d87d8a0026f2/gistfile1.txt). The ``compile-dotnet-assemblies.bat`` script needs the .NET updates that are currently available. Leaving the updates enabled will result in a successful build.

**Comment by sneal** [comment]
Fortunately the happy path is to install Windows updates, but that can be frustrating when trying to debug. I'm not sure there's anything we can do about this, but this issue documents the problem and "workaround".

@avtar If there's something more specific you think we should do here, LMK.
