### ISSUE TITLE
WinRM - Windows 10 Enterprise Evaluation is not working with new ISO?

### ISSUE THREAD

**Issue by Real2014** [joefitzgerald/packer-windows#187]
I've tested the WinRM branch with Win 2012 (EN) and (German), both working without problems.

Yesterday tested the same thing with Win 10 (EN) and works to ! 

But the german iso is stopping at startup at the first step. 
![bild 3](https://cloud.githubusercontent.com/assets/9336264/11929804/6ecf4136-a7de-11e5-9aa2-4cdd15fb695c.png)

Could it be because it is a new ISO Version with TH2 instead of TH1 ? (Because the working english ISO is a TH1 Version).

Here are the Info's if someone wants to reproduce the problem and wants to check out the issue:

http://care.dlservice.microsoft.com/dl/download/C/8/2/C827FD6A-C114-4CFD-9A3F-D14FE468A081/10586.0.151029-1700.TH2_RELEASE_CLIENTENTERPRISEEVAL_OEMRET_X64FRE_DE-DE.ISO

MD5: a7bcf12c1103785a68ed5808548c164f
SHA1: 369c7c96bfbe9728531b8b24cd10abdc7b5ca1ee1

Has someone a direct link to the older German TH1 Version, couldn't find a link with Google. Maybe the scripts are working the older ISO Version?

**Comment by StefanScherer** [comment]
@Real2014 You can check if the new ISO needs a different string for the `InstallFrom` tag in the Autounattend.xml. The TH1 had `Windows 10 Enterprise Evaluation`. You can check the strings within another VM by mounting the ISO to a drive letter ( the example below uses E: ) and then call

```
dism /Get-WimInfo /WimFile:E:\sources\install.wim
```

**Comment by StefanScherer** [comment]
@Real2014 try again with `Windows 10 Enterprise Evaluation Technical Preview` in answer_files/10/Autounattend.xml

**Comment by Real2014** [comment]
@StefanScherer Thank you for the hint. Didn't know that I have to look for a different string for the ISO's and have to change that. I checked the ISO and yes, dism says that name for the ISO is ' Beschreibung: "Windows 10 Enterprise Evaluation Technical Preview" '

![bild 4](https://cloud.githubusercontent.com/assets/9336264/12088483/fbf43d7a-b2db-11e5-9abb-769a9efb8bea.png)

I will check the Installation again with a new autounattend.xml File and will report here later :)

**Comment by Real2014** [comment]
OK. After changing the Autounattend.xml to the right string, the Install Routine is starting and everything is working well with one problem. 

At the end of the process, packer is not compressing the machine into a zip file but halting with an error.

*Build 'vmware-iso' errored: Shutdown command has non-zero exit status.
Stdout:
Stderr: Die Schnittstelle ist unbekannt.(1717)*

![bild 6](https://cloud.githubusercontent.com/assets/9336264/12092013/e0ca377e-b2fa-11e5-9fca-ce02a68f505e.png)

**Comment by StefanScherer** [comment]
@Real2014 please have a look at https://www.packer.io/docs/other/debugging.html

**Comment by Real2014** [comment]
Thanks for the hint again.

Maybe the packer Debug Website should be updated. In Windows Powershell, the -debug Parameter was working but to start the build with Parameter PACKER_LOG=1 is not working. Powershell tells one that he don't know what to do with PACKER_LOG=1.

Under Windows Powershell one has to type:

	$env:PACKER_LOG=1
	$env:PACKER_LOG_PATH="C:\packer_path\log\packer_log.txt"
	.\packer build -force -only=vmware-iso windows_10_de.json

First I found out through the Log File that powershell wasn't really using the new packer 0.8.6 that I downloaded a few month ago. It was using the old 0.7.1 Version because there was an entry in system environment that i forgot to change.

Now I'm running the packer build step again to find out what went wrong with the build process.

Will report here again later.

**Comment by Real2014** [comment]
Everything worked well this time. 

No more errors with Packer/WinRM and German Windows 10 ISO File.

The Log File showed no errors. The only errors were for waiting for WinRM.

Thank you for the quick help @StefanScherer  :+1:

**Comment by Real2014** [comment]
Had to take that back. The error happened once again when I started the build process yesterday evening again. The Log file is telling me of problems with deleting the vm-disk files because another process is using them ???

	2016/01/05 17:59:22 ui: ==> vmware-iso: Stopping virtual machine...
	2016/01/05 17:59:22 packer-builder-vmware-iso.exe: 2016/01/05 17:59:22 Executing: C:/Program Files (x86)/VMware/VMware Workstation/vmrun.exe [-T ws stop output-vmware-iso\packer-vmware-iso.vmx hard]
	2016/01/05 17:59:26 packer-builder-vmware-iso.exe: 2016/01/05 17:59:26 stdout:
	2016/01/05 17:59:26 packer-builder-vmware-iso.exe: 2016/01/05 17:59:26 stderr:
	2016/01/05 17:59:26 packer-builder-vmware-iso.exe: 2016/01/05 17:59:26 Deleting floppy disk: C:\Users\ADCC7~1.CEL\AppData\Local\Temp\packer745430939
	2016/01/05 17:59:26 ui: ==> vmware-iso: Deleting output directory...
	2016/01/05 17:59:26 packer-builder-vmware-iso.exe: 2016/01/05 17:59:26 Error removing output dir: remove output-vmware-iso\disk-s001.vmdk: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
	2016/01/05 17:59:28 ui error: Build 'vmware-iso' errored: Restart script exited with non-zero exit status: 1
	2016/01/05 17:59:28 Builds completed. Waiting on interrupt barrier...
	2016/01/05 17:59:28 machine readable: error-count []string{"1"}
	2016/01/05 17:59:28 ui error: 
	==> Some builds didn't complete successfully and had errors:
	2016/01/05 17:59:28 machine readable: vmware-iso,error []string{"Restart script exited with non-zero exit status: 1"}
	2016/01/05 17:59:28 ui error: --> vmware-iso: Restart script exited with non-zero exit status: 1
	2016/01/05 17:59:28 ui: 
	==> Builds finished but no artifacts were created.

**Comment by StefanScherer** [comment]
@Real2014 I sometimes got this error, seems to be a brittle bug in packer itself.

**Comment by Real2014** [comment]
@StefanScherer  Thank you for the information :+1: 

I'm closing the Issue now.

**Comment by Hattener** [comment]
Get windows 10 product key here:# http://plus.google.com/u/0/110027797061234891794
