### ISSUE TITLE
Running windows_7 

### ISSUE THREAD

**Issue by DriveU** [joefitzgerald/packer-windows#189]
from the packer-windows-jf-switch-to-winrm branch get the following error almost at the end using Windows 7 Ultimate iso locally available in the .iso folder.
Before modifying the windows 7 decided that I should first run everything as is.
Any idea what am I missing? 
    vmware-iso: C:\Users\vagrant>reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyT
SConnections /t REG_DWORD /d 0 /f
    vmware-iso: The operation completed successfully.
==> vmware-iso: Provisioning with shell script: ./scripts/compile-dotnet-assemblies.bat
    vmware-iso: The system cannot find the path specified.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>if "AMD64" == "AMD64" goto 64BIT
    vmware-iso:
    vmware-iso: C:\Users\vagrant>C:\Windows\microsoft.net\framework\v4.0.30319\ngen.exe update /force /queue
    vmware-iso:
    vmware-iso: C:\Users\vagrant>C:\Windows\microsoft.net\framework64\v4.0.30319\ngen.exe update /force /queue
    vmware-iso:
    vmware-iso: C:\Users\vagrant>C:\Windows\microsoft.net\framework\v4.0.30319\ngen.exe executequeueditems
    vmware-iso:
    vmware-iso: C:\Users\vagrant>C:\Windows\microsoft.net\framework64\v4.0.30319\ngen.exe executequeueditems
    vmware-iso: The system cannot find the path specified.
    vmware-iso: The system cannot find the path specified.
    vmware-iso: The system cannot find the path specified.
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Script exited with non-zero exit status: 1

**Comment by mrled** [comment]
Are you applying Windows Updates? Apparently, a vanilla Win7 ISO doesn't have ngen.exe where compile-dotnet-assemblies.bat expects it to be, and it's also a different version which has caused people some problems, per https://github.com/joefitzgerald/packer-windows/issues/161.

**Comment by LukB4ULeap** [comment]
No I have disabled Windows Updates in my answer file

**Comment by sneal** [comment]
Closing, same issue open elsewhere.
