### ISSUE TITLE
windows 8.1 -- ==> virtualbox-iso: Waiting for SSH to become available...

### ISSUE THREAD

**Issue by shamimgeek** [joefitzgerald/packer-windows#190]
packer.io --version
0.8.6
vagrant --version
Vagrant 1.7.4
vboxmanage --version
4.3.26r98988
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///usr/share/virtualbox/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: file:///home/test/9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_ENTERPRISE_EVAL_EN-US-IR3_CENA_X64FREE_EN-US_DV9.ISO
==> virtualbox-iso: Creating floppy disk...
    virtualbox-iso: Copying: ./answer_files/81/Autounattend.xml
    virtualbox-iso: Copying: ./scripts/microsoft-updates.bat
    virtualbox-iso: Copying: ./scripts/win-updates.ps1
    virtualbox-iso: Copying: ./scripts/openssh.ps1
    virtualbox-iso: Copying: ./scripts/oracle-cert.cer
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Attaching floppy disk...
==> virtualbox-iso: Creating forwarded port mapping for SSH (host port 2234)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1452035245 --memory 2048
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1452035245 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
    virtualbox-iso: WARNING: The VM will be started in headless mode, as configured.
    virtualbox-iso: In headless mode, errors during the boot sequence or OS setup
    virtualbox-iso: won't be easily visible. Use at your own discretion.
==> virtualbox-iso: Waiting 2m0s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become availa

**Comment by StefanScherer** [comment]
@shamimgeek please change the `"headless": true` to `"headless": false` in the `windows_81.json` file. Then you can see what happens, maybe it hangs selecting the right version to be installed as shown in many other issues here in this repo. If that is the case you have to update the `answer_files/81/Autounattend.xml` for your local ISO file. Default is `Windows 8.1 Enterprise Evaluation` and there you have to set the right string matching for your ISO.
