### ISSUE TITLE
Win7 - Downloading Updates fails

### ISSUE THREAD

**Issue by strowi** [joefitzgerald/packer-windows#193]
Hi,

quite new to packer & co. I was trying to get a Win7 built, but got the attached error while downloading the Updates...

![win7_updates](https://cloud.githubusercontent.com/assets/589662/12219090/6f5b7c04-b734-11e5-99a2-a4763672f653.jpg)

regards,
strowi

**Comment by sneal** [comment]
I see this error too, but you can safely ignore it. It retries the download 30s later which works, reboots, then continues installing more updates.

I'm not sure why this happens on Win7 on initial run of the script. It could be a race condition between the script and the automatic update service.
