### ISSUE TITLE
Windows 10 Provisioning fails with 127 in Compile-DotNet-Assemblies

### ISSUE THREAD

**Issue by tommyziegler** [joefitzgerald/packer-windows#198]
The provisioning of a Windows 10 VM fails in the post step to compile the Compile-DotNet-Assemblies (./scripts/compile-dotnet-assemblies.bat). This was made for old Windows version to work around slow VM startup. Does anyone know if I could remove it for Windows 10, because when I do so the creating works fine.

Thx for your help Tommy

**Comment by sneal** [comment]
The step is completely optional and can be safely removed. The script doesn't work on Windows7 either, see #150. I'm wondering what version of Windows and .NET it does work on.

**Comment by sneal** [comment]
I put in a workaround so at least if the ngen compilation fails the box build continues on. See #199.
