### ISSUE TITLE
Windows 2012 r2 server template

### ISSUE THREAD

**Issue by Rapso** [joefitzgerald/packer-windows#208]
There is issue with this template,  when installator after collecting informations ask if we want install core only, or with gui version. It does stops then.

**Comment by rperez31** [comment]
Hey Guys, 

I got this working on my VirtualBox, I was wondering how do I implement this in our Vsphere?

**Comment by StefanScherer** [comment]
@Rapso It seems that your ISO does not fit to [the selection in the Autounattend.xml](https://github.com/joefitzgerald/packer-windows/blob/a48400f13fb44f91862a7d58960f53b3d7ffb5d9/answer_files/2012_r2/Autounattend.xml#L54). So the installer stops asking for the right selection. You may have to update the Autounattend.xml for your ISO.

@rperez31 Have a look at https://www.packer.io/docs/post-processors/vsphere.html how to add vShere into the packer templates. Maybe some real world examples at https://github.com/tsugliani/packer-vsphere-templates may help you.
