### ISSUE TITLE
Add Windows Server 2016

### ISSUE THREAD

**Issue by StefanScherer** [joefitzgerald/packer-windows#211]
I have a working packer template for Windows Server 2016 TP5 in [my fork](https://github.com/StefanScherer/packer-windows) and in the long term I want to merge that back into this repo. Especially I'm working on a base box including the Windows Docker engine. 

There is one minor issue with the autounattend.xml, it seems that the product key is not recognized in the xml. So I just added some keyboard input from the packer template.json file.

I'm not sure of sending a PR now or wait until PR #205 is done to avoid some collisions.

**Comment by StefanScherer** [comment]
Problem with the product key is fixed. Thanks to @mwieczorek who has fixed it in https://github.com/StefanScherer/packer-windows/commit/80b526a6203612dfd31c38b3fef6b6901151151a by adding the ProductKey tag in the Microsoft-Windows-Shell-Setup which was new to me. For a core installation this is not needed, but for a GUI installation of TP5.

**Comment by lmayorga1980** [comment]
:+1:

**Comment by basictheprogram** [comment]
Adding for reference https://github.com/joefitzgerald/packer-windows/pull/243

**Comment by StefanScherer** [comment]
Fixed with #243
