### ISSUE TITLE
windows_7 not working

### ISSUE THREAD

**Issue by apvancedemo** [joefitzgerald/packer-windows#224]
Hi,

I am using Packer 0.10.1 and VirtualBox 5.0.28.

I have uploaded my windows_7.json file. I didn't change any of the other files.

[windows_7.zip](https://github.com/joefitzgerald/packer-windows/files/553328/windows_7.zip)

---
==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://care.dlservice.microsoft.com/dl/download/evalx/win7/x64/EN/7600.16385.090713-1255_x64fre_enterprise_en-us_EVAL_Eval_Enterprise-GRMCENXEVAL_EN_DVD.iso
==> virtualbox-iso: Creating floppy disk...
    virtualbox-iso: Copying: ./answer_files/7/Autounattend.xml
    virtualbox-iso: Copying: ./scripts/dis-updates.ps1
    virtualbox-iso: Copying: ./scripts/hotfix-KB3102810.bat
    virtualbox-iso: Copying: ./scripts/microsoft-updates.bat
    virtualbox-iso: Copying: ./scripts/win-updates.ps1
    virtualbox-iso: Copying: ./scripts/openssh.ps1
    virtualbox-iso: Copying: ./scripts/oracle-cert.cer
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Attaching floppy disk...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 3993)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1477446704 --memory 2048
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1477446704 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
    virtualbox-iso: The VM will be run headless, without a GUI. If you want to
    virtualbox-iso: view the screen of the VM, connect via VRDP without a password to
    virtualbox-iso: 127.0.0.1:5972
==> virtualbox-iso: Waiting 2m0s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for WinRM to become available...
==> virtualbox-iso: Timeout waiting for WinRM.
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Timeout waiting for WinRM.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Timeout waiting for WinRM.

==> Builds finished but no artifacts were created.

**Comment by rajeshr264** [comment]
FYI: packer-windows/windows_7.json just works (Yay!), ONLY if you are on a "Windows 7 Professional " PC!!! 

Don't waste your time running 'packer-windows/windows_7.json' on a Mac.
