### ISSUE TITLE
VBox Guest Additions fails on VBOX 5.1.22

### ISSUE THREAD

**Issue by lmayorga1980** [joefitzgerald/packer-windows#244]
I am sure this is not related to packer but wondering if someone tested the latest vbox with packer-windows and got the `vm-guest-tools.bat` to pass.

Found someone had issues on `5.1.22` guest tools on linux.
https://github.com/dotless-de/vagrant-vbguest/issues/251

**Comment by lmayorga1980** [comment]
It actually does not fail but it does not appear under Installed Programs and VirtualBox does not provide any other silent arguments to install it fully.

**Comment by sh4jonny** [comment]
hi! how you fix it ?
