### ISSUE TITLE
Creating vmx file to deploy onto vSphere

### ISSUE THREAD

**Issue by kief** [joefitzgerald/packer-windows#27]
Hi, I'm quite happy to be able to use packer to build Windows images thanks to this project. I want to deploy VMs (actually, VM templates are my end goal) onto a vSphere instance, but haven't managed it yet.

I have modified the packer configuration, adding '"keep_input_artifact": true' to the vagrant builder, and tried running ovftool on the .vmx file that gets created in the output directory.

But ovftool fails because it has a path to floppy0, which doesn't exist.

Error message:

```
Error: File (/var/folders/zl/57c1vmr532z_ryf1scw53_b9ycmxh7/T/packer964492999) could not be found.
```

From the .vmx file:

```
floppy0.filename = "/var/folders/zl/57c1vmr532z_ryf1scw53_b9ycmxh7/T/packer964492999"
floppy0.filetype = "file"
floppy0.present = "TRUE"
```

So I'm not sure if there's a way to generate the .vmx file without the floppy drive - presumably, once the OS has been installed and we don't need the Autounattend.xml file anymore, it can be detached.

Is there a change needed to the config file to make this work, or something else I could do? I could post-process the .vmx file to disable the drive, but it feels like a hack. Either I'm doing something wrong, or there's an improvement to be made somewhere.

Thanks,
Kief

**Comment by bigmyx** [comment]
had the same issue.
it worked after adding `ovftool` post-processor before `vsphere`.
