### ISSUE TITLE
Generate Packer JSON Files

### ISSUE THREAD

**Issue by joefitzgerald** [joefitzgerald/packer-windows#3]
Picking up the conversation where we left off in Dylan's pull request: #1 .

I think there are a few dimensions that are required for a minimally useful packer-windows template:

* Operating System Version
    * Windows 7
    * Windows 2008 R2
    * Windows 8
    * Windows 2012
    * Windows 8.1
    * Windows 2012 R2
* Operating System Edition
    * Desktop
        * Windows 7
            * Starter
            * Home Basic
            * Home Professional
            * Professional
            * Enterprise
            * Ultimate
        * Windows 8
            * Windows 8
            * Pro
            * Enterprise
    * Server
        * Standard
        * Enterprise
        * Datacenter
* Builder
    * VMware
    * VirtualBox
    * Others
* Provisioners
    * Script
    * PowerShell
    * Chef
    * Puppet
    * Other

If we could provide some level of reuse at each level (OS Version, OS Edition, Builder, Provisioner), that would hopefully drastically reduce the number of distinct .json files we manage (because we can generate them). 

I agree with Shawn that we need to maintain the ability to customize, which could be achieved via the build process, or by providing hooks for extensibility (e.g. if user defined script x exists, run it after the core provisioning steps). Also, there's nothing stopping someone from taking a .json file we generate and then customizing it from there.

Does that make sense? Do you think I'm missing any obvious requirements?

**Comment by sneal** [comment]
Fixed by #200
