### ISSUE TITLE
Problems invoking puppet-masterless after using scripts/puppet.bat

### ISSUE THREAD

**Issue by raniemi** [joefitzgerald/packer-windows#46]
What I'm trying to do is repurpose the `windows_2008_r2.json` file by swapping out `scripts/chef.bat` for `scripts/puppet.bat` and then calling out to `puppet-masterless` to install and run my manifests.  

The `scripts/puppet.bat` file is being executed and puppet is being installed correctly. However, once `puppet apply` is invoked by `puppet-masterless` the `execute_command` is shown, but my manifest is not being executed and no additional output/errors are shown (even with PACKER_LOG=1 set).

For testing purposes, I have been using the following custom `execute_command`:

```
"execute_command": " \
    {{.FacterVars}}puppet apply \
        --debug \
        --logdest='C:/Windows/Temp/puppet-apply.log' \
        --modulepath='{{.ModulePath}}' \
        --manifestdir='{{.ManifestDir}}' \
        --detailed-exitcodes \
        -e 'include rubyinstaller' \
"
```

NOTES: 
- The spacing and EOL \s were added here for readability purposes only
- I am using packer 0.5.2
- When the execute_command "runs", the `logdest` file does not get created
- I have even tried specifying the absolute path to puppet's bat file under Program Files just in case the guest OS PATH was not visible at the time puppet-masterless ran -- no effect
- When I pause packer after the puppet-masterless step and I execute the generated `execute_command` at the guest Windows VM's command prompt, the execution works.
- The (custom) "rubyinstaller" module that I'm using is attempting to install `rubyinstaller` in "verysilent" mode.  Has anyone seen any limitations with puppet-masterless when using an installer on windows that requires a desktop?
- I've also noticed on Windows with packer that if puppet apply fails or a shell script returns a non-zero `ERRORLEVEL`, packer keeps on going.  Any suggestions on how to fail-fast? (EDIT: this bullet looks suspiciously like joefitzgerald/packer-windows#45)
- I only know this from the occasional warning that I'm seeing, but It appears that `cygwin` is being used under the covers by puppet-masterless. Any other gotchas I should keep in mind when working with custom `execute_commands`?

I realize that some of these questions may be best asked on the packer forum, but since these questions are very windows specific, I'm wondering if other trailblazers here have already encountered and resolved these issues.

**Comment by sulaweyo** [comment]
I see how this workaround can be applied but i fail to see how an awkward workaround can close this issue. The functionality is not there and even if you can do the same via a workaround the bug still exists. I mean there is a provisioner that is not working for windows.

**Comment by petemounce** [comment]
Seems like packer has an open tracking bug hashicorp/packer#2566.
